
export const defaultPartnershipAgreement = {
    en: `# INDEPENDENT CONTRACTOR AGREEMENT
## For Content Creators

### 1. PURPOSE OF AGREEMENT
1.1. The Contractor owns and operates one or more YouTube channels, social media accounts, or other digital content platforms (collectively "Channels") and wishes to receive administrative, monetization, training, and operational support from the Company.
1.2. The Contractor remains the sole creator of all content, retains full ownership of all Channels, and retains the absolute right to discontinue this Agreement at any time without penalty or restriction.
1.3. This Agreement establishes a non-exclusive, independent contractor relationship for the purpose of revenue optimization and administrative support only.

### 2. CHANNEL OWNERSHIP AND INTELLECTUAL PROPERTY RIGHTS
2.1. CHANNEL OWNERSHIP: The Contractor is and shall remain the sole lawful owner of the Channels listed in this Agreement or attached schedules.
2.2. NO TRANSFER OF OWNERSHIP: Nothing in this Agreement transfers, assigns, or conveys any ownership, intellectual property rights, publishing rights, distribution rights, or any other proprietary rights to the Company.
2.3. CONTENT RIGHTS: The Company does not claim, and shall never claim, any rights, title, or interest in content created, published, stored, or distributed through the Channels; trademarks, logos, or brand elements associated with the Channels; subscriber/follower relationships or audience data; or future content or derivative works.
2.4. CONTRACTOR RETAINS ALL RIGHTS: The Contractor retains 100% ownership and control over Channel login credentials and administrator access; all content (past, present, and future); Channel monetization settings; brand partnerships and sponsorship agreements; and merchandise and affiliate marketing rights.

### 3. CONTRACTOR OBLIGATIONS AND CREATIVE FREEDOM
3.1. SOLE RESPONSIBILITY: The Contractor is solely and exclusively responsible for content creation, ideation, and production; publishing schedules and frequency; editorial decisions and creative direction; copyright compliance and licensing; compliance with platform Terms of Service (YouTube, Instagram, TikTok, etc.); community management and audience engagement; and brand safety and advertiser-friendly content guidelines.
3.2. CREATIVE INDEPENDENCE: The Contractor independently chooses and controls content topics, themes, and subject matter; video/post formats, styles, and production quality; languages and target audiences; publication schedules and upload frequency; collaborations and guest appearances; and monetization strategies (ads, memberships, super chats, etc.).
3.3. NO MINIMUM REQUIREMENTS: The Contractor is NOT required to produce a minimum number of videos/posts; maintain a specific upload schedule; achieve specific performance metrics; or follow Company content guidelines or editorial direction.

### 4. COMPANY OBLIGATIONS AND SERVICES
4.1. ADMINISTRATIVE SUPPORT: The Company shall provide monetization management through advertising revenue systems; revenue tracking and financial reporting for each Channel; timely distribution of Contractor revenue share; access to analytics dashboards and performance reports; administrative support related to monetization optimization; payment processing and international transfer facilitation; and optional training resources and growth strategy consultation.
4.2. NON-CONTROL COMMITMENT: The Company shall NOT control, influence, or restrict content decisions; require specific content types or topics; impose editorial guidelines or censorship; demand minimum performance metrics; or interfere with creative freedom.
4.3. TRANSPARENCY OBLIGATION: The Company commits to full transparency regarding revenue received from platforms; administrative fees deducted; payment processing timelines; and any changes to revenue models or fee structures.

### 5. REVENUE MODEL AND PAYMENT TERMS
5.1. REVENUE ALLOCATION: All revenue generated by or paid to the Channels listed in Section 2 through YouTube AdSense, platform monetization, or affiliated advertising systems shall be allocated as follows: Contractor Share: 99.5% (ninety-nine point five percent); Company Administrative Fee: 0.5% (zero point five percent).
5.2. REVENUE DEFINITION: "Revenue" includes all income from YouTube AdSense advertising, YouTube Premium revenue share, platform-provided monetization features, and any other platform-distributed advertising revenue. "Revenue" EXCLUDES direct sponsorships negotiated by Contractor, affiliate marketing commissions, merchandise sales, and Super Chats, memberships, or tips (unless otherwise agreed).
5.3. PAYMENT PROCESSING: The Company receives monthly payouts from YouTube/platforms. Within 7 (seven) business days of receiving platform payouts, the Company shall calculate and transfer the Contractor's 99.5% share. Payments shall be made via the Contractor's chosen method (Bank Transfer, Western Union, etc.).
5.4. MONTHLY STATEMENTS: The Company shall provide detailed monthly statements showing gross revenue received from platforms, Company administrative fee (0.5%), net amount paid to Contractor (99.5%), and payment date and transaction reference.
5.5. MINIMUM PAYOUT THRESHOLD: Payments shall be processed when the Contractor's share reaches a minimum of USD $100 / EUR €100.

### 6. TAX RESPONSIBILITIES
6.1. CONTRACTOR TAX OBLIGATIONS: The Contractor acknowledges and agrees that they are fully responsible for all tax filings in their country of residence, income tax declarations and payments, Value Added Tax (VAT) or Sales Tax compliance (if applicable), social security contributions (if applicable), and any other tax obligations arising from income received.
6.2. COMPANY TAX OBLIGATIONS: The Company is responsible solely for tax obligations on its administrative fee (0.5%) in accordance with Swedish tax law.
6.3. GROSS PAYMENTS: All payments to the Contractor are GROSS amounts and do NOT include tax withholding. The Contractor must handle all tax obligations independently.
6.4. TAX DOCUMENTATION: Upon request, the Company shall provide annual revenue summaries, payment records, and transaction history.
6.5. NO TAX ADVICE: The Company does not provide tax advice. The Contractor is advised to consult with a qualified tax professional in their jurisdiction.

### 7. ACCESS RIGHTS AND CHANNEL CONTROLS
7.1. CONTRACTOR RETAINS FULL CONTROL: The Contractor retains full administrator ownership and primary control of all Channels at all times.
7.2. LIMITED COMPANY ACCESS: The Company may be granted LIMITED access ONLY for analytics review and performance monitoring, monetization configuration and optimization, brand safety review and advertiser compliance, and technical troubleshooting related to monetization.
7.3. ACCESS RESTRICTIONS: The Company shall NOT have access to channel login credentials (username/password), email account associated with the Channel, content upload or publishing capabilities, community post creation or comment moderation, or channel settings or branding modifications.
7.4. REVOCATION OF ACCESS: The Contractor may revoke Company access at any time, immediately and without cause, by removing Company user permissions from the Channel, notifying the Company via email, or submitting a Termination Notice.
7.5. EARNED FEES PROTECTION: Revocation of access does not nullify the Company's right to collect earned administrative fees (0.5%) for revenue generated up to the date of revocation.

### 8. RIGHT TO TERMINATE
8.1. IMMEDIATE TERMINATION RIGHT: The Contractor may terminate this Agreement IMMEDIATELY, at any time, for any reason or no reason, with NO PENALTY, NO FEES, and NO RESTRICTIONS by completing and submitting the "Termination Notice Form" or sending written notice via email.
8.2. NO NOTICE PERIOD REQUIRED: The Contractor is NOT required to provide advance notice. Termination is effective immediately upon submission of the Termination Notice.
8.3. EFFECTS OF TERMINATION: Upon termination, the Company loses all access rights to the Channel(s), stops collecting revenue, settles all outstanding payments within 14 calendar days, and deletes or returns any Contractor data. Channel ownership, control, and all rights remain 100% with the Contractor.
8.4. NO RESTRICTIONS ON CONTRACTOR: The Company shall NOT restrict or delay channel ownership transfer or access; impose penalties, fees, or charges for termination; withhold payments or revenue; interfere with Channel operations post-termination; or claim any ongoing rights to content or revenue.
8.5. FINAL SETTLEMENT: Within 14 days of termination, the Company shall provide final payment, a final revenue statement, confirmation of access removal, and confirmation of data deletion.

### 9. NON-INTERFERENCE CLAUSE
9.1. PROHIBITED COMPANY ACTIONS: The Company shall NOT modify, edit, or alter channel content; publish, upload, or schedule content without explicit prior approval; restrict, influence, or interfere with editorial decisions; impose publishing rules, content guidelines, or creative restrictions; delete or remove published content; respond to comments or engage with the audience on behalf of the Contractor; or make channel branding or design changes.
9.2. CONTRACTOR INDEPENDENCE: The Contractor has full, independent, and unrestricted creative and business freedom regarding all aspects of Channel operations.
9.3. ADVISORY ROLE ONLY: The Company may provide suggestions, recommendations, or best practices, but the Contractor has sole discretion to accept or reject such advice.

### 10. INDEPENDENT CONTRACTOR STATUS
10.1. NO EMPLOYMENT RELATIONSHIP: Nothing in this Agreement creates, implies, or establishes an employment relationship, an employer-employee relationship, labor-based dependency, social benefits or employment benefits, working obligations, or exclusive service obligations.
10.2. CONTRACTOR INDEPENDENCE: The Contractor is an independent business entity and independently determines workload volume, schedule, deliverable frequency, and work methods.
10.3. NO EMPLOYEE BENEFITS: The Contractor is NOT entitled to paid vacation or sick leave, health insurance, pension contributions, unemployment benefits, or workers' compensation.
10.4. BUSINESS EXPENSES: The Contractor is responsible for all business expenses including equipment, internet, production costs, travel, and training.

### 11. CONFIDENTIALITY AND DATA PROTECTION
11.1. COMPANY CONFIDENTIALITY OBLIGATIONS: The Company shall NOT disclose, share, or make public earnings data, channel analytics, contact information, personal identity information, or payment details without the Contractor's explicit written permission.
11.2. DATA PROTECTION: The Company commits to comply with GDPR and applicable data protection laws, securely store all Contractor data, use data only for purposes specified in this Agreement, and delete or return data upon termination.
11.3. CONTRACTOR RIGHTS: The Contractor has the right to request access to their data, request correction of inaccurate data, request deletion of data, and object to data processing.

### 12. DISPUTE RESOLUTION AND GOVERNING LAW
12.1. GOOD FAITH NEGOTIATION: In the event of any dispute, the parties shall first attempt to resolve the matter through good-faith negotiation within 30 calendar days.
12.2. MEDIATION: If negotiation fails, the parties agree to attempt mediation before pursuing litigation.
12.3. GOVERNING LAW: This Agreement shall be governed by and construed in accordance with the laws of Sweden.
12.4. JURISDICTION: Any legal action shall be brought exclusively in the courts of Sweden.
12.5. LANGUAGE: The official language of this Agreement is English. Any translations are for convenience only.

### 13. MISCELLANEOUS PROVISIONS
13.1. AMENDMENTS: Any amendments must be made in writing and signed by both parties.
13.2. SEVERABILITY: If any provision is found to be invalid, the remaining provisions shall remain in full force and effect.
13.3. WAIVER: Failure to enforce any provision shall not constitute a waiver.
13.4. ASSIGNMENT: The Contractor may assign this Agreement. The Company may not assign without consent.
13.5. NOTICES: All notices shall be sent to nor.volvera@gmail.com for the Company and the Contractor's email.
13.6. FORCE MAJEURE: Neither party shall be liable for failure to perform obligations due to circumstances beyond their reasonable control.

### 14. ENTIRE AGREEMENT
14.1. This document constitutes the entire agreement between the Company and the Contractor.
14.2. This Agreement supersedes all prior negotiations, understandings, agreements, representations, and warranties.
14.3. No verbal agreements, promises, or representations shall be binding unless incorporated into this written Agreement.

### 15. SIGNATURES
BY SIGNING BELOW, BOTH PARTIES ACKNOWLEDGE THAT THEY HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY ALL TERMS AND CONDITIONS OF THIS INDEPENDENT CONTRACTOR AGREEMENT.
`,

    fa: `# قرارداد پیمانکار مستقل
## برای تولیدکنندگان محتوا

### ۱. هدف قرارداد
۱.۱. پیمانکار مالکیت و مدیریت یک یا چند کانال یوتیوب، حساب‌های رسانه‌های اجتماعی، یا سایر پلتفرم‌های محتوای دیجیتال (مجموعاً "کانال‌ها") را بر عهده دارد و مایل است از خدمات اداری، درآمدزایی، آموزشی و عملیاتی شرکت بهره‌مند شود.
۱.۲. پیمانکار تنها خالق تمام محتوا باقی می‌ماند، مالکیت کامل تمام کانال‌ها را حفظ می‌کند و حق مطلق دارد که این قرارداد را در هر زمان بدون جریمه یا محدودیت فسخ کند.
۱.۳. این قرارداد یک رابطه پیمانکار مستقل غیرانحصاری را صرفاً به منظور بهینه‌سازی درآمد و پشتیبانی اداری ایجاد می‌کند.

### ۲. مالکیت کانال و حقوق مالکیت فکری
۲.۱. مالکیت کانال: پیمانکار مالک قانونی و انحصاری کانال‌های ذکر شده در این قرارداد یا پیوست‌ها است و باقی خواهد ماند.
۲.۲. عدم انتقال مالکیت: هیچ چیزی در این قرارداد هیچ‌گونه مالکیت، حقوق مالکیت فکری، حقوق نشر، حقوق توزیع یا سایر حقوق انحصاری را به شرکت منتقل یا واگذار نمی‌کند.
۲.۳. حقوق محتوا: شرکت هیچ‌گونه حق، عنوان یا منافعی در محتوای ایجاد شده، علائم تجاری، لوگوها، روابط با مشترکین/دنبال‌کنندگان یا محتوای آینده ادعا نمی‌کند و نخواهد کرد.
۲.۴. حفظ تمام حقوق توسط پیمانکار: پیمانکار ۱۰۰٪ مالکیت و کنترل خود بر اعتبارنامه‌های ورود به کانال، تمام محتوا (گذشته، حال و آینده)، تنظیمات درآمدزایی، و قراردادهای تجاری را حفظ می‌کند.

### ۳. تعهدات پیمانکار و آزادی خلاقانه
۳.۱. مسئولیت انحصاری: پیمانکار به‌طور انحصاری مسئول ایجاد محتوا، برنامه‌های انتشار، تصمیمات ویرایشی، رعایت کپی‌رایت، رعایت شرایط خدمات پلتفرم (یوتیوب، اینستاگرام و غیره)، و مدیریت جامعه مخاطبین است.
۳.۲. استقلال خلاقانه: پیمانکار به‌طور مستقل موضوعات محتوا، فرمت‌ها، زبان‌ها، برنامه‌های انتشار و استراتژی‌های درآمدزایی را انتخاب و کنترل می‌کند.
۳.۳. بدون الزامات حداقل: پیمانکار ملزم به تولید تعداد مشخصی ویدئو، رعایت برنامه زمان‌بندی خاص، یا دستیابی به معیارهای عملکردی خاص نیست.

### ۴. تعهدات و خدمات شرکت
۴.۱. پشتیبانی اداری: شرکت خدماتی مانند مدیریت درآمدزایی، گزارش‌دهی مالی، توزیع سهم درآمد پیمانکار، دسترسی به تحلیل‌ها، و پردازش پرداخت‌ها را ارائه می‌دهد.
۴.۲. تعهد عدم کنترل: شرکت محتوا را کنترل یا محدود نمی‌کند، دستورالعمل‌های ویرایشی تحمیل نمی‌کند و در آزادی خلاقانه مداخله نمی‌کند.
۴.۳. شفافیت: شرکت متعهد به شفافیت کامل در مورد درآمد دریافتی، کارمزدهای اداری کسر شده و زمان‌های پردازش پرداخت است.

### ۵. مدل درآمد و شرایط پرداخت
۵.۱. تخصیص درآمد: تمام درآمد حاصل از کانال‌ها به شرح زیر تقسیم می‌شود: سهم پیمانکار: ۹۹.۵٪ (نود و نه و نیم درصد)؛ کارمزد اداری شرکت: ۰.۵٪ (نیم درصد).
۵.۲. تعریف درآمد: "درآمد" شامل تمام درآمدهای تبلیغاتی یوتیوب و پلتفرم‌هاست. این شامل اسپانسری‌های مستقیم، فروش کالا یا کمک‌های مالی شخصی نمی‌شود.
۵.۳. پردازش پرداخت: شرکت ظرف ۷ روز کاری پس از دریافت پرداخت از پلتفرم‌ها، سهم ۹۹.۵٪ پیمانکار را محاسبه و منتقل می‌کند.
۵.۴. صورت‌حساب‌های ماهانه: شرکت صورت‌حساب‌های دقیقی از درآمد ناخالص، کارمزد شرکت و مبلغ خالص پرداختی به پیمانکار ارائه می‌دهد.
۵.۵. حداقل آستانه پرداخت: پرداخت‌ها زمانی انجام می‌شود که سهم پیمانکار به حداقل ۱۰۰ دلار آمریکا / ۱۰۰ یورو برسد.

### ۶. مسئولیت‌های مالیاتی
۶.۱. تعهدات مالیاتی پیمانکار: پیمانکار مسئول تمام امور مالیاتی، اظهارنامه‌های درآمد و پرداخت‌ها در کشور محل اقامت خود است.
۶.۲. تعهدات مالیاتی شرکت: شرکت تنها مسئول تعهدات مالیاتی مربوط به کارمزد اداری خود (۰.۵٪) طبق قوانین سوئد است.
۶.۳. پرداخت‌های ناخالص: تمام پرداخت‌ها به پیمانکار به صورت ناخالص بوده و شامل کسر مالیات نمی‌شود.
۶.۴. اسناد مالیاتی: در صورت درخواست، شرکت سوابق درآمد و تراکنش‌ها را ارائه می‌دهد.
۶.۵. عدم مشاوره مالیاتی: شرکت مشاوره مالیاتی ارائه نمی‌دهد. پیمانکار باید با یک متخصص مالیاتی مشورت کند.

### ۷. حقوق دسترسی و کنترل کانال
۷.۱. کنترل کامل پیمانکار: پیمانکار مالکیت و کنترل اصلی تمام کانال‌ها را همیشه حفظ می‌کند.
۷.۲. دسترسی محدود شرکت: شرکت ممکن است تنها برای بررسی تحلیل‌ها، تنظیمات درآمدزایی و عیب‌یابی فنی دسترسی محدود داشته باشد.
۷.۳. محدودیت‌های دسترسی: شرکت به رمزهای عبور، ایمیل، قابلیت انتشار محتوا یا تنظیمات برندینگ دسترسی نخواهد داشت.
۷.۴. لغو دسترسی: پیمانکار می‌تواند در هر زمان دسترسی شرکت را لغو کند.
۷.۵. حفظ کارمزدها: لغو دسترسی حق شرکت برای دریافت کارمزد درآمدهای ایجاد شده تا آن تاریخ را باطل نمی‌کند.

### ۸. حق فسخ
۸.۱. حق فسخ فوری: پیمانکار می‌تواند این قرارداد را فوراً، در هر زمان و بدون جریمه با ارسال اطلاعیه کتبی فسخ کند.
۸.۲. بدون نیاز به اطلاع قبلی: فسخ بلافاصله پس از ارسال اطلاعیه موثر است.
۸.۳. اثرات فسخ: پس از فسخ، شرکت دسترسی خود را از دست می‌دهد، جمع‌آوری درآمد را متوقف می‌کند و تمام پرداخت‌های معوقه را ظرف ۱۴ روز تسویه می‌کند.
۸.۴. عدم محدودیت: شرکت هیچ جریمه‌ای برای فسخ اعمال نمی‌کند و در عملیات کانال مداخله نمی‌کند.
۸.۵. تسویه نهایی: شرکت ظرف ۱۴ روز پرداخت نهایی و تأییدیه حذف دسترسی را ارائه می‌دهد.

### ۹. عدم مداخله
۹.۱. اقدامات ممنوعه: شرکت محتوا را تغییر نمی‌دهد، بدون تأیید محتوا منتشر نمی‌کند و در تصمیمات ویرایشی مداخله نمی‌کند.
۹.۲. استقلال پیمانکار: پیمانکار آزادی کامل تجاری و خلاقانه دارد.
۹.۳. نقش مشاوره‌ای: شرکت ممکن است پیشنهادات ارائه دهد، اما پیمانکار در پذیرش آن‌ها مختار است.

### ۱۰. وضعیت پیمانکار مستقل
۱۰.۱. عدم رابطه استخدامی: این قرارداد رابطه کارمند و کارفرما ایجاد نمی‌کند.
۱۰.۲. استقلال: پیمانکار زمان و روش کار خود را تعیین می‌کند.
۱۰.۳. عدم مزایای کارمندی: پیمانکار حق دریافت مرخصی، بیمه درمانی یا مزایای بیکاری را ندارد.
۱۰.۴. هزینه‌های تجاری: پیمانکار مسئول تمام هزینه‌های تجهیزات و تولید است.

### ۱۱. محرمانگی و حفاظت از داده‌ها
۱۱.۱. تعهدات محرمانگی: شرکت اطلاعات درآمدی و شخصی پیمانکار را بدون اجازه فاش نمی‌کند.
۱۱.۲. حفاظت از داده‌ها: شرکت از قوانین GDPR پیروی کرده و داده‌ها را ایمن نگه می‌دارد.
۱۱.۳. حقوق پیمانکار: پیمانکار حق دسترسی، اصلاح و حذف داده‌های خود را دارد.

### ۱۲. حل اختلاف و قانون حاکم
۱۲.۱. مذاکره: طرفین ابتدا تلاش می‌کنند اختلافات را از طریق مذاکره حل کنند.
۱۲.۲. میانجی‌گری: اگر مذاکره شکست بخورد، طرفین به میانجی‌گری متوسل می‌شوند.
۱۲.۳. قانون حاکم: این قرارداد تابع قوانین سوئد است.
۱۲.۴. صلاحیت قضایی: دادگاه‌های سوئد صلاحیت انحصاری دارند.
۱۲.۵. زبان: زبان رسمی قرارداد انگلیسی است.

### ۱۳. مقررات متفرقه
۱۳.۱. اصلاحات: هرگونه اصلاحیه باید کتبی باشد.
۱۳.۲. تفکیک‌پذیری: اگر بخشی از قرارداد نامعتبر باشد، بقیه معتبر باقی می‌ماند.
۱۳.۳. واگذاری: پیمانکار می‌تواند قرارداد را واگذار کند، اما شرکت خیر.
۱۳.۴. فورس ماژور: هیچ‌یک از طرفین مسئول حوادث غیرقابل کنترل نیستند.

### ۱۴. تمام توافق
۱۴.۱. این سند تمام توافقات بین طرفین را تشکیل می‌دهد و جایگزین مذاکرات قبلی است.

### ۱۵. امضاها
با امضای زیر، طرفین تایید می‌کنند که تمام شرایط این قرارداد را خوانده، درک کرده و با آن موافقت می‌کنند.
`,

    ps: `# د خپلواک قراردادي تړون
## د منځپانګې جوړونکو لپاره

### ۱. د تړون موخه
۱.۱. قراردادي د یو یا ډیرو یوټیوب چینلونو، ټولنیزو رسنیو حسابونو، یا ډیجیټل پلیټ فارمونو (په ټولیز ډول "چینلونه") مالک دی او غواړي د شرکت څخه اداري او عایداتي ملاتړ ترلاسه کړي.
۱.۲. قراردادي د ټولو منځپانګو یوازینی جوړونکی پاتې کیږي، د ټولو چینلونو بشپړ مالکیت ساتي، او حق لري چې دا تړون هر وخت پرته له جریمې فسخ کړي.
۱.۳. دا تړون یوازې د عاید او اداري ملاتړ لپاره یو غیر انحصاری خپلواک قراردادي اړیکه رامینځته کوي.

### ۲. د چینل مالکیت او فکري ملکیت حقونه
۲.۱. د چینل مالکیت: قراردادي د لیست شوي چینلونو قانوني او یوازینی مالک دی او پاتې به وي.
۲.۲. د مالکیت نه لیږد: پدې تړون کې هیڅ شی شرکت ته د مالکیت، فکري ملکیت، یا خپرولو حقونه نه لیږدوي.
۲.۳. د منځپانګې حقونه: شرکت د منځپانګې، نښو، یا د لیدونکو ډاټا کې هیڅ حق نه لري.
۲.۴. قراردادي ټول حقونه ساتي: قراردادي د چینل د ننوتلو معلوماتو، منځپانګې، او عایداتي تنظیماتو ۱۰۰٪ کنټرول ساتي.

### ۳. د قراردادي مکلفیتونه او تخلیقي آزادي
۳.۱. یوازینی مسؤلیت: قراردادي د منځپانګې جوړولو، مهال ویش، اداری پریکړو، او د کاپي حق مراعاتولو مسؤل دی.
۳.۲. تخلیقي خپلواکي: قراردادي په خپلواکه توګه موضوعات، سټایلونه، ژبې، او د خپرولو مهال ویش ټاکي.
۳.۳. هیڅ لږترلږه اړتیاوې نشته: قراردادي اړ ندی چې د ویډیوګانو لږترلږه شمیر تولید کړي یا د شرکت لارښوونې تعقیب کړي.

### ۴. د شرکت مکلفیتونه او خدمات
۴.۱. اداري ملاتړ: شرکت د عاید مدیریت، مالي راپور ورکول، د تادیاتو پروسس کول، او تحلیلونو ته لاسرسی چمتو کوي.
۴.۲. د نه کنټرول ژمنه: شرکت به د منځپانګې پریکړې کنټرول یا محدود نکړي او په تخلیقي آزادي کې مداخله ونکړي.
۴.۳. روڼتیا: شرکت د ترلاسه شوي عاید او اداري فیسونو په اړه بشپړ روڼتیا ته ژمن دی.

### ۵. د عاید ماډل او د تادیې شرایط
۵.۱. د عاید ویش: د چینلونو څخه ترلاسه شوی ټول عاید په لاندې ډول ویشل کیږي: د قراردادي برخه: ۹۹.۵٪؛ د شرکت اداري فیس: ۰.۵٪.
۵.۲. د عاید تعریف: په عاید کې د یوټیوب اعلاناتو عاید شامل دی، مګر مستقیم سپन्सरشپونه یا د توکو پلور پکې شامل ندي.
۵.۳. د تادیې پروسس کول: شرکت د پلیټ فارم تادیاتو ترلاسه کولو وروسته په ۷ کاري ورځو کې د قراردادي برخه لیږي.
۵.۴. میاشتني بیانونه: شرکت به د ناخالص عاید او فیسونو په اړه تفصیلي میاشتني بیانونه وړاندې کړي.
۵.۵. د تادیې لږترلږه حد: تادیات هغه وخت ترسره کیږي کله چې د قراردادي برخه لږترلږه ۱۰۰ ډالرو / ۱۰۰ یورو ته ورسیږي.

### ۶. مالیاتي مسؤلیتونه
۶.۱. د قراردادي مالیاتي مکلفیتونه: قراردادي د خپل هیواد په قوانینو کې د ټولو مالیاتو مسؤل دی.
۶.۲. د شرکت مالیاتي مکلفیتونه: شرکت یوازې په خپل اداري فیس (۰.۵٪) باندې د مالیاتو مسؤل دی.
۶.۳. ناخالص تادیات: قراردادي ته ټول تادیات ناخالص دي او مالیه پکې نه کمیږي.
۶.۴. مالیاتي اسناد: شرکت به د غوښتنې په صورت کې د عاید ریکارډونه چمتو کړي.
۶.۵. هیڅ مالیاتي مشوره نشته: قراردادي باید د خپل مالیاتي مشاور سره مشوره وکړي.

### ۷. د لاسرسي حقونه او د چینل کنټرول
۷.۱. د قراردادي بشپړ کنټرول: قراردادي هر وخت د چینلونو بشپړ کنټرول ساتي.
۷.۲. محدود لاسرسی: شرکت یوازې د تحلیلونو او عاید تنظیم کولو لپاره محدود لاسرسی لري.
۷.۳. محدودیتونه: شرکت به د ننوتلو معلوماتو یا د منځپانګې خپرولو ته لاسرسی ونلري.
۷.۴. د لاسرسي لغوه کول: قراردادي کولی شي هر وخت د شرکت لاسرسی لغوه کړي.
۷.۵. د فیسونو ساتنه: د لاسرسي لغوه کول د ګټل شوي فیسونو حق نه اغیزه کوي.

### ۸. د فسخ کولو حق
۸.۱. سمدستي فسخ کول: قراردادي کولی شي دا تړون هر وخت سمدستي او پرته له جریمې فسخ کړي.
۸.۲. هیڅ خبرتیا ته اړتیا نشته: فسخ کول د خبرتیا لیږلو سره سم اغیزمن دي.
۸.۳. د فسخې پایلې: شرکت لاسرسی له لاسه ورکوي او ټولې پاتې تادیات په ۱۴ ورځو کې ترسره کوي.
۸.۴. هیڅ محدودیت نشته: شرکت د فسخ کولو لپاره هیڅ جریمه نه اخلي.
۸.۵. وروستی تصفیه: شرکت په ۱۴ ورځو کې وروستۍ تادیه او حساب ورکوي.

### ۹. نه مداخله
۹.۱. منع شوي اقدامات: شرکت به منځپانګه نه بدلوي او نه به په اداری پریکړو کې مداخله کوي.
۹.۲. خپلواکي: قراردادي بشپړ تخلیقي او سوداګریزه آزادي لري.
۹.۳. مشورتي رول: شرکت یوازې وړاندیزونه ورکولی شي.

### ۱۰. د خپلواک قراردادي حالت
۱۰.۱. د کارموندنې اړیکه نشته: دا تړون د کارمند او کارفرما اړیکه نه رامینځته کوي.
۱۰.۲. خپلواکي: قراردادي خپل کاري ساعتونه او میتودونه پخپله ټاکي.
۱۰.۳. د کارمند ګټې نشته: قراردادي د رخصتۍ یا بیمې حق نلري.
۱۰.۴. لګښتونه: قراردادي د خپلو ټولو سوداګریزو لګښتونو مسؤل دی.

### ۱۱. محرمیت او د معلوماتو ساتنه
۱۱.۱. محرمیت: شرکت به شخصي او عایداتي معلومات نه افشا کوي.
۱۱.۲. د معلوماتو ساتنه: شرکت به د معلوماتو ساتنې قوانین مراعات کړي.
۱۱.۳. حقونه: قراردادي خپلو معلوماتو ته د لاسرسي او حذف کولو حق لري.

### ۱۲. د شخړو حل او حاکم قانون
۱۲.۱. خبرې اترې: لومړی به ستونزې د خبرو اترو له لارې حل کیږي.
۱۲.۲. منځګړیتوب: که خبرې اترې ناکامې شي، منځګړیتوب به ترسره شي.
۱۲.۳. حاکم قانون: دا تړون د سویډن د قوانینو تابع دی.
۱۲.۴. محکمه: قانوني اقدامات به په سویډن کې ترسره کیږي.
۱۲.۵. ژبه: اصلي ژبه انګلیسي ده.

### ۱۳. متفرقه احکام
۱۳.۱. تعدیلات: بدلونونه باید لیکلي وي.
۱۳.۲. اعتبار: که یوه برخه باطله وي، نورې برخې معتبرې پاتې کیږي.
۱۳.۳. واک سپارل: قراردادي کولی شي تړون بل ته وسپاري.
۱۳.۴. اضطراري حالت: هیڅ لوری د کنټرول څخه بهر پیښو مسؤل ندی.

### १४. بشپړ تړون
۱۴.۱. دا سند د دواړو خواوو ترمنځ بشپړ تړون جوړوي.

### ۱۵. لاسلیکونه
د لاندې لاسلیک کولو سره، دواړه خواوې مني چې د دې تړون ټول شرایط یې لوستلي او ورسره موافق دي.
`
};

export const defaultTerminationNotice = {
    en: `# TERMINATION NOTICE FORM

## 1. PARTIES
This Termination Notice is submitted by the CONTRACTOR to the COMPANY (VOLVERA).

## 2. NOTICE OF TERMINATION
I, the undersigned Contractor, hereby give notice to terminate the Independent Contractor Agreement.

## 3. EFFECTIVE DATE
This termination is effective immediately upon submission of this form.

## 4. ACKNOWLEDGMENT
I understand that upon termination:
- The Company's access to my channels will be revoked.
- Any outstanding payments will be settled within 14 days.
- Data held by the Company will be deleted or returned.

## 5. SIGNATURE
By submitting this form, I confirm my intent to terminate the agreement.
`,

    fa: `# فرم فسخ قرارداد

## ۱. طرفین
این اطلاعیه فسخ توسط پیمانکار به شرکت (VOLVERA) ارائه می‌شود.

## ۲. اطلاعیه فسخ
من، پیمانکار امضاکننده زیر، بدینوسیله فسخ قرارداد پیمانکار مستقل را اعلام می‌کنم.

## ۳. تاریخ اجرا
این فسخ بلافاصله پس از ارسال این فرم لازم‌الاجرا است.

## ۴. تاییدیه
من درک می‌کنم که پس از فسخ:
- دسترسی شرکت به کانال‌های من لغو خواهد شد.
- هرگونه پرداخت معوقه ظرف ۱۴ روز تسویه خواهد شد.
- داده‌های نگهداری شده توسط شرکت حذف یا بازگردانده خواهند شد.

## ۵. امضا
با ارسال این فرم، من قصد خود برای فسخ قرارداد را تایید می‌کنم.
`,

    ps: `# د فسخې خبرتیا فورمه

## ۱. خواوې
د فسخې دا خبرتیا د قراردادي لخوا شرکت (VOLVERA) ته سپارل کیږي.

## ۲. د فسخې خبرتیا
زه، لاندې لاسلیک کونکی قراردادي، په دې توګه د خپلواک قراردادي تړون د فسخ کولو خبر ورکوم.

## ۳. د پلي کیدو نیټه
دا فسخه د دې فورمې سپارلو سره سم سمدستي اغیزمنه ده.

## ۴. تصدیق
زه پوهیږم چې د فسخې وروسته:
- زما چینلونو ته د شرکت لاسرسی به لغو شي.
- ټولې پاتې تادیات به په ۱۴ ورځو کې تسویه شي.
- د شرکت لخوا ساتل شوي معلومات به حذف یا بیرته ورکړل شي.

## ۵. لاسلیک
د دې فورمې په سپارلو سره، زه د تړون فسخ کولو اراده تاییدوم.
`
};
